==================================
Test session for 0-add_integer.py
==================================
This module only contains one function:
* add_integer()

Importing function from module.

>>> add_integer = __import__("0-add_integer").add_integer

' Positive integers '
>>> add_integer(1, 2)
3


' Negative integers '
>>> add_integer(-1, -2)
-3


' Positive and negative integers'
>>> add_integer(1, -2)
-1


' Only first integer given '
>>> add_integer(1)
99


' Long integer '
>>> add_integer(333333333333333333333333333333333333, 1)
333333333333333333333333333333333334


' Second parameter not given '
>>> add_integer(1, )
99


' Multiple parameters passed '
>>> [add_integer(i, i + 2) for i in range(4)]
[2, 4, 6, 8]


' Function without parameters '
>>> add_integer()
Traceback (most recent call last):
...
TypeError: add_integer() missing 1 required positional argument: 'a'


' String as first parameter '
>>> add_integer("str", 3)
Traceback (most recent call last):
...
TypeError: a must be an integer


' Floating points as parameters '
>>> add_integer(1.5, 1.5)
2


' Negative floating points'
>>> add_integer(-1.5, -1.5)
-2


' Floating and integers parameters '
>>> add_integer(2, 2.5)
4


' Complex values '
>>> add_integer(complex(1, 2), 1)
Traceback (most recent call last):
...
TypeError: a must be an integer


' Range as one parameter '
>>> add_integer(1, range(2))
Traceback (most recent call last):
...
TypeError: b must be an integer


' None as one parameter '
>>> add_integer(None, )
Traceback (most recent call last):
...
TypeError: a must be an integer


' Boolean parameter '
>>> add_integer(1, True)
Traceback (most recent call last):
...
TypeError: b must be an integer


' More than two parameters '
>>> add_integer(1, 2, 3)
Traceback (most recent call last):
...
TypeError: add_integer() takes from 1 to 2 positional arguments but 3 were given


' Impossible integer '
>>> add_integer(1, 4/0)
Traceback (most recent call last):
...
ZeroDivisionError: division by zero


' Not a number as parameter '
>>> add_integer(1, float("NaN"))
Traceback (most recent call last):
...
ValueError: cannot convert float NaN to integer
